INSERT INTO customer VALUES ('1', '0992347882');
INSERT INTO customer VALUES ('2', '0998587741');
INSERT INTO customer VALUES ('3', '0946487096');
INSERT INTO customer VALUES ('4', '0945831054');
INSERT INTO customer VALUES ('5', '0931515384');
INSERT INTO customer VALUES ('6', '0950584866');
INSERT INTO customer VALUES ('7', '0921058112');
INSERT INTO customer VALUES ('8', '0911500645');
INSERT INTO customer VALUES ('9', '0933679759');
INSERT INTO customer VALUES ('10', '0987471076');
INSERT INTO customer VALUES ('11', '0965130875');
INSERT INTO customer VALUES ('12', '0927970194');
INSERT INTO customer VALUES ('13', '0974686479');
INSERT INTO customer VALUES ('14', '0976065521');
INSERT INTO customer VALUES ('15', '0925949256');
INSERT INTO customer VALUES ('16', '0965598003');
INSERT INTO customer VALUES ('17', '0971491913');
INSERT INTO customer VALUES ('18', '0933911096');
INSERT INTO customer VALUES ('19', '0985026012');
INSERT INTO customer VALUES ('20', '0970093831');
INSERT INTO product VALUES ('1', '8冰烏', 'static/product_images/8冰烏_40.jpg', '40');
INSERT INTO product VALUES ('2', '8冰紅', 'static/product_images/8冰紅_40.jpg', '40');
INSERT INTO product VALUES ('3', '8冰綠', 'static/product_images/8冰綠_40.jpg', '40');
INSERT INTO product VALUES ('4', '8冰茶', 'static/product_images/8冰茶_40.jpg', '40');
INSERT INTO product VALUES ('5', '8冰青', 'static/product_images/8冰青_40.jpg', '40');
INSERT INTO product VALUES ('6', '冰淇淋四季拿鐵', 'static/product_images/冰淇淋四季拿鐵_55.jpg', '55');
INSERT INTO product VALUES ('7', '冰淇淋奶綠', 'static/product_images/冰淇淋奶綠_50.jpg', '50');
INSERT INTO product VALUES ('8', '冰淇淋奶茶', 'static/product_images/冰淇淋奶茶_50.jpg', '50');
INSERT INTO product VALUES ('9', '冰淇淋奶青', 'static/product_images/冰淇淋奶青_50.jpg', '50');
INSERT INTO product VALUES ('10', '冰淇淋烏龍', 'static/product_images/冰淇淋烏龍_40.jpg', '40');
INSERT INTO product VALUES ('11', '冰淇淋烏龍奶', 'static/product_images/冰淇淋烏龍奶_50.jpg', '50');
INSERT INTO product VALUES ('12', '冰淇淋紅茶', 'static/product_images/冰淇淋紅茶_40.jpg', '40');
INSERT INTO product VALUES ('13', '冰淇淋紅茶拿鐵', 'static/product_images/冰淇淋紅茶拿鐵_55.jpg', '55');
INSERT INTO product VALUES ('14', '冰淇淋綠茶', 'static/product_images/冰淇淋綠茶_40.jpg', '40');
INSERT INTO product VALUES ('15', '冰淇淋綠茶拿鐵', 'static/product_images/冰淇淋綠茶拿鐵_55.jpg', '55');
INSERT INTO product VALUES ('16', '冰淇淋重焙烏龍拿鐵', 'static/product_images/冰淇淋重焙烏龍拿鐵_55.jpg', '55');
INSERT INTO product VALUES ('17', '冰淇淋阿華田', 'static/product_images/冰淇淋阿華田_50.jpg', '50');
INSERT INTO product VALUES ('18', '冰淇淋青茶', 'static/product_images/冰淇淋青茶_40.jpg', '40');
INSERT INTO product VALUES ('19', '可可芭蕾', 'static/product_images/可可芭蕾_50.jpg', '50');
INSERT INTO product VALUES ('20', '可可芭蕾拿鐵', 'static/product_images/可可芭蕾拿鐵_55.jpg', '55');
INSERT INTO product VALUES ('21', '四季拿鐵', 'static/product_images/四季拿鐵_50.jpg', '50');
INSERT INTO product VALUES ('22', '四季春青茶', 'static/product_images/四季春青茶_30.jpg', '30');
INSERT INTO product VALUES ('23', '多多烏', 'static/product_images/多多烏_40.jpg', '40');
INSERT INTO product VALUES ('24', '多多紅', 'static/product_images/多多紅_40.jpg', '40');
INSERT INTO product VALUES ('25', '多多綠', 'static/product_images/多多綠_40.jpg', '40');
INSERT INTO product VALUES ('26', '多多青', 'static/product_images/多多青_40.jpg', '40');
INSERT INTO product VALUES ('27', '奶綠', 'static/product_images/奶綠_40.jpg', '40');
INSERT INTO product VALUES ('28', '奶茶', 'static/product_images/奶茶_40.jpg', '40');
INSERT INTO product VALUES ('29', '奶青', 'static/product_images/奶青_40.jpg', '40');
INSERT INTO product VALUES ('30', '布丁四季拿鐵', 'static/product_images/布丁四季拿鐵_55.jpg', '55');
INSERT INTO product VALUES ('31', '布丁奶綠', 'static/product_images/布丁奶綠_50.jpg', '50');
INSERT INTO product VALUES ('32', '布丁奶茶', 'static/product_images/布丁奶茶_50.jpg', '50');
INSERT INTO product VALUES ('33', '布丁奶青', 'static/product_images/布丁奶青_50.jpg', '50');
INSERT INTO product VALUES ('34', '布丁烏龍奶', 'static/product_images/布丁烏龍奶_50.jpg', '50');
INSERT INTO product VALUES ('35', '布丁紅茶拿鐵', 'static/product_images/布丁紅茶拿鐵_55.jpg', '55');
INSERT INTO product VALUES ('36', '布丁綠茶拿鐵', 'static/product_images/布丁綠茶拿鐵_55.jpg', '55');
INSERT INTO product VALUES ('37', '布丁重焙烏龍拿鐵', 'static/product_images/布丁重焙烏龍拿鐵_55.jpg', '55');
INSERT INTO product VALUES ('38', '布丁阿華田', 'static/product_images/布丁阿華田_50.jpg', '50');
INSERT INTO product VALUES ('39', '微檸檬烏龍', 'static/product_images/微檸檬烏龍_35.jpg', '35');
INSERT INTO product VALUES ('40', '微檸檬紅茶', 'static/product_images/微檸檬紅茶_35.jpg', '35');
INSERT INTO product VALUES ('41', '微檸檬綠茶', 'static/product_images/微檸檬綠茶_35.jpg', '35');
INSERT INTO product VALUES ('42', '微檸檬青茶', 'static/product_images/微檸檬青茶_35.jpg', '35');
INSERT INTO product VALUES ('43', '情人茶', 'static/product_images/情人茶_40.jpg', '40');
INSERT INTO product VALUES ('44', '旺來烏龍', 'static/product_images/旺來烏龍_40.jpg', '40');
INSERT INTO product VALUES ('45', '旺來紅', 'static/product_images/旺來紅_40.jpg', '40');
INSERT INTO product VALUES ('46', '旺來綠', 'static/product_images/旺來綠_40.jpg', '40');
INSERT INTO product VALUES ('47', '旺來青', 'static/product_images/旺來青_40.jpg', '40');
INSERT INTO product VALUES ('48', '柚子烏龍', 'static/product_images/柚子烏龍_40.jpg', '40');
INSERT INTO product VALUES ('49', '柚子紅', 'static/product_images/柚子紅_40.jpg', '40');
INSERT INTO product VALUES ('50', '柚子綠', 'static/product_images/柚子綠_40.jpg', '40');
INSERT INTO product VALUES ('51', '柚子茶', 'static/product_images/柚子茶_40.jpg', '40');
INSERT INTO product VALUES ('52', '柚子青', 'static/product_images/柚子青_40.jpg', '40');
INSERT INTO product VALUES ('53', '桔子汁', 'static/product_images/桔子汁_50.jpg', '50');
INSERT INTO product VALUES ('54', '梅烏', 'static/product_images/梅烏_40.jpg', '40');
INSERT INTO product VALUES ('55', '梅紅', 'static/product_images/梅紅_40.jpg', '40');
INSERT INTO product VALUES ('56', '梅綠', 'static/product_images/梅綠_40.jpg', '40');
INSERT INTO product VALUES ('57', '梅青', 'static/product_images/梅青_40.jpg', '40');
INSERT INTO product VALUES ('58', '椰果可可芭蕾', 'static/product_images/椰果可可芭蕾_50.jpg', '50');
INSERT INTO product VALUES ('59', '椰果可可芭蕾拿鐵', 'static/product_images/椰果可可芭蕾拿鐵_55.jpg', '55');
INSERT INTO product VALUES ('60', '椰果四季拿鐵', 'static/product_images/椰果四季拿鐵_50.jpg', '50');
INSERT INTO product VALUES ('61', '椰果奶綠', 'static/product_images/椰果奶綠_40.jpg', '40');
INSERT INTO product VALUES ('62', '椰果奶茶', 'static/product_images/椰果奶茶_40.jpg', '40');
INSERT INTO product VALUES ('63', '椰果奶青', 'static/product_images/椰果奶青_40.jpg', '40');
INSERT INTO product VALUES ('64', '椰果烏龍', 'static/product_images/椰果烏龍_35.jpg', '35');
INSERT INTO product VALUES ('65', '椰果烏龍奶', 'static/product_images/椰果烏龍奶_40.jpg', '40');
INSERT INTO product VALUES ('66', '椰果紅茶', 'static/product_images/椰果紅茶_35.jpg', '35');
INSERT INTO product VALUES ('67', '椰果紅茶拿鐵', 'static/product_images/椰果紅茶拿鐵_50.jpg', '50');
INSERT INTO product VALUES ('68', '椰果綠茶', 'static/product_images/椰果綠茶_35.jpg', '35');
INSERT INTO product VALUES ('69', '椰果綠茶拿鐵', 'static/product_images/椰果綠茶拿鐵_50.jpg', '50');
INSERT INTO product VALUES ('70', '椰果重焙烏龍拿鐵', 'static/product_images/椰果重焙烏龍拿鐵_50.jpg', '50');
INSERT INTO product VALUES ('71', '椰果阿華田', 'static/product_images/椰果阿華田_40.jpg', '40');
INSERT INTO product VALUES ('72', '椰果阿華田拿鐵', 'static/product_images/椰果阿華田拿鐵_50.jpg', '50');
INSERT INTO product VALUES ('73', '椰果青茶', 'static/product_images/椰果青茶_35.jpg', '35');
INSERT INTO product VALUES ('74', '檸檬多多', 'static/product_images/檸檬多多_55.jpg', '55');
INSERT INTO product VALUES ('75', '檸檬梅汁', 'static/product_images/檸檬梅汁_50.jpg', '50');
INSERT INTO product VALUES ('76', '檸檬梅烏', 'static/product_images/檸檬梅烏_40.jpg', '40');
INSERT INTO product VALUES ('77', '檸檬梅紅', 'static/product_images/檸檬梅紅_40.jpg', '40');
INSERT INTO product VALUES ('78', '檸檬梅青', 'static/product_images/檸檬梅青_40.jpg', '40');
INSERT INTO product VALUES ('79', '檸檬汁', 'static/product_images/檸檬汁_50.jpg', '50');
INSERT INTO product VALUES ('80', '檸檬烏龍', 'static/product_images/檸檬烏龍_40.jpg', '40');
INSERT INTO product VALUES ('81', '檸檬紅茶', 'static/product_images/檸檬紅茶_40.jpg', '40');
INSERT INTO product VALUES ('82', '檸檬綠茶', 'static/product_images/檸檬綠茶_40.jpg', '40');
INSERT INTO product VALUES ('83', '檸檬蜜', 'static/product_images/檸檬蜜_55.jpg', '55');
INSERT INTO product VALUES ('84', '檸檬青茶', 'static/product_images/檸檬青茶_40.jpg', '40');
INSERT INTO product VALUES ('85', '波霸可可芭蕾', 'static/product_images/波霸可可芭蕾_50.jpg', '50');
INSERT INTO product VALUES ('86', '波霸可可芭蕾拿鐵', 'static/product_images/波霸可可芭蕾拿鐵_55.jpg', '55');
INSERT INTO product VALUES ('87', '波霸四季拿鐵', 'static/product_images/波霸四季拿鐵_50.jpg', '50');
INSERT INTO product VALUES ('88', '波霸奶綠', 'static/product_images/波霸奶綠_40.jpg', '40');
INSERT INTO product VALUES ('89', '波霸奶茶', 'static/product_images/波霸奶茶_40.jpg', '40');
INSERT INTO product VALUES ('90', '波霸奶青', 'static/product_images/波霸奶青_40.jpg', '40');
INSERT INTO product VALUES ('91', '波霸烏龍', 'static/product_images/波霸烏龍_35.jpg', '35');
INSERT INTO product VALUES ('92', '波霸烏龍奶', 'static/product_images/波霸烏龍奶_40.jpg', '40');
INSERT INTO product VALUES ('93', '波霸紅茶', 'static/product_images/波霸紅茶_35.jpg', '35');
INSERT INTO product VALUES ('94', '波霸紅茶拿鐵', 'static/product_images/波霸紅茶拿鐵_50.jpg', '50');
INSERT INTO product VALUES ('95', '波霸綠茶', 'static/product_images/波霸綠茶_35.jpg', '35');
INSERT INTO product VALUES ('96', '波霸綠茶拿鐵', 'static/product_images/波霸綠茶拿鐵_50.jpg', '50');
INSERT INTO product VALUES ('97', '波霸重焙烏龍拿鐵', 'static/product_images/波霸重焙烏龍拿鐵_50.jpg', '50');
INSERT INTO product VALUES ('98', '波霸阿華田', 'static/product_images/波霸阿華田_40.jpg', '40');
INSERT INTO product VALUES ('99', '波霸阿華田拿鐵', 'static/product_images/波霸阿華田拿鐵_50.jpg', '50');
INSERT INTO product VALUES ('100', '波霸青茶', 'static/product_images/波霸青茶_35.jpg', '35');
INSERT INTO product VALUES ('101', '烏龍奶', 'static/product_images/烏龍奶_40.jpg', '40');
INSERT INTO product VALUES ('102', '烏龍瑪奇朵', 'static/product_images/烏龍瑪奇朵_40.jpg', '40');
INSERT INTO product VALUES ('103', '燕麥可可芭蕾', 'static/product_images/燕麥可可芭蕾_50.jpg', '50');
INSERT INTO product VALUES ('104', '燕麥可可芭蕾拿鐵', 'static/product_images/燕麥可可芭蕾拿鐵_55.jpg', '55');
INSERT INTO product VALUES ('105', '燕麥四季拿鐵', 'static/product_images/燕麥四季拿鐵_50.jpg', '50');
INSERT INTO product VALUES ('106', '燕麥奶綠', 'static/product_images/燕麥奶綠_40.jpg', '40');
INSERT INTO product VALUES ('107', '燕麥奶茶', 'static/product_images/燕麥奶茶_40.jpg', '40');
INSERT INTO product VALUES ('108', '燕麥奶青', 'static/product_images/燕麥奶青_40.jpg', '40');
INSERT INTO product VALUES ('109', '燕麥烏龍', 'static/product_images/燕麥烏龍_35.jpg', '35');
INSERT INTO product VALUES ('110', '燕麥烏龍奶', 'static/product_images/燕麥烏龍奶_40.jpg', '40');
INSERT INTO product VALUES ('111', '燕麥紅茶', 'static/product_images/燕麥紅茶_35.jpg', '35');
INSERT INTO product VALUES ('112', '燕麥紅茶拿鐵', 'static/product_images/燕麥紅茶拿鐵_50.jpg', '50');
INSERT INTO product VALUES ('113', '燕麥綠茶', 'static/product_images/燕麥綠茶_35.jpg', '35');
INSERT INTO product VALUES ('114', '燕麥綠茶拿鐵', 'static/product_images/燕麥綠茶拿鐵_50.jpg', '50');
INSERT INTO product VALUES ('115', '燕麥重焙烏龍拿鐵', 'static/product_images/燕麥重焙烏龍拿鐵_50.jpg', '50');
INSERT INTO product VALUES ('116', '燕麥阿華田', 'static/product_images/燕麥阿華田_40.jpg', '40');
INSERT INTO product VALUES ('117', '燕麥阿華田拿鐵', 'static/product_images/燕麥阿華田拿鐵_50.jpg', '50');
INSERT INTO product VALUES ('118', '燕麥青茶', 'static/product_images/燕麥青茶_35.jpg', '35');
INSERT INTO product VALUES ('119', '珍波椰青茶', 'static/product_images/珍波椰青茶_35.jpg', '35');
INSERT INTO product VALUES ('120', '珍珠可可芭蕾', 'static/product_images/珍珠可可芭蕾_50.jpg', '50');
INSERT INTO product VALUES ('121', '珍珠可可芭蕾拿鐵', 'static/product_images/珍珠可可芭蕾拿鐵_55.jpg', '55');
INSERT INTO product VALUES ('122', '珍珠四季拿鐵', 'static/product_images/珍珠四季拿鐵_50.jpg', '50');
INSERT INTO product VALUES ('123', '珍珠奶綠', 'static/product_images/珍珠奶綠_40.jpg', '40');
INSERT INTO product VALUES ('124', '珍珠奶茶', 'static/product_images/珍珠奶茶_40.jpg', '40');
INSERT INTO product VALUES ('125', '珍珠奶青', 'static/product_images/珍珠奶青_40.jpg', '40');
INSERT INTO product VALUES ('126', '珍珠烏龍', 'static/product_images/珍珠烏龍_35.jpg', '35');
INSERT INTO product VALUES ('127', '珍珠烏龍奶', 'static/product_images/珍珠烏龍奶_40.jpg', '40');
INSERT INTO product VALUES ('128', '珍珠紅茶', 'static/product_images/珍珠紅茶_35.jpg', '35');
INSERT INTO product VALUES ('129', '珍珠紅茶拿鐵', 'static/product_images/珍珠紅茶拿鐵_50.jpg', '50');
INSERT INTO product VALUES ('130', '珍珠綠茶', 'static/product_images/珍珠綠茶_35.jpg', '35');
INSERT INTO product VALUES ('131', '珍珠綠茶拿鐵', 'static/product_images/珍珠綠茶拿鐵_50.jpg', '50');
INSERT INTO product VALUES ('132', '珍珠重焙烏龍拿鐵', 'static/product_images/珍珠重焙烏龍拿鐵_50.jpg', '50');
INSERT INTO product VALUES ('133', '珍珠阿華田', 'static/product_images/珍珠阿華田_40.jpg', '40');
INSERT INTO product VALUES ('134', '珍珠阿華田拿鐵', 'static/product_images/珍珠阿華田拿鐵_50.jpg', '50');
INSERT INTO product VALUES ('135', '珍珠青茶', 'static/product_images/珍珠青茶_35.jpg', '35');
INSERT INTO product VALUES ('136', '紅茶拿鐵', 'static/product_images/紅茶拿鐵_50.jpg', '50');
INSERT INTO product VALUES ('137', '紅茶瑪奇朵', 'static/product_images/紅茶瑪奇朵_40.jpg', '40');
INSERT INTO product VALUES ('138', '綠茶拿鐵', 'static/product_images/綠茶拿鐵_50.jpg', '50');
INSERT INTO product VALUES ('139', '綠茶瑪奇朵', 'static/product_images/綠茶瑪奇朵_40.jpg', '40');
INSERT INTO product VALUES ('140', '芒果奶綠', 'static/product_images/芒果奶綠_50.jpg', '50');
INSERT INTO product VALUES ('141', '芒果奶茶', 'static/product_images/芒果奶茶_50.jpg', '50');
INSERT INTO product VALUES ('142', '芒果奶青', 'static/product_images/芒果奶青_50.jpg', '50');
INSERT INTO product VALUES ('143', '芒果烏龍', 'static/product_images/芒果烏龍_40.jpg', '40');
INSERT INTO product VALUES ('144', '芒果烏龍奶', 'static/product_images/芒果烏龍奶_50.jpg', '50');
INSERT INTO product VALUES ('145', '芒果紅茶', 'static/product_images/芒果紅茶_40.jpg', '40');
INSERT INTO product VALUES ('146', '芒果綠茶', 'static/product_images/芒果綠茶_40.jpg', '40');
INSERT INTO product VALUES ('147', '芒果青茶', 'static/product_images/芒果青茶_40.jpg', '40');
INSERT INTO product VALUES ('148', '茉莉綠茶', 'static/product_images/茉莉綠茶_30.jpg', '30');
INSERT INTO product VALUES ('149', '荔枝奶綠', 'static/product_images/荔枝奶綠_50.jpg', '50');
INSERT INTO product VALUES ('150', '荔枝奶茶', 'static/product_images/荔枝奶茶_50.jpg', '50');
INSERT INTO product VALUES ('151', '荔枝奶青', 'static/product_images/荔枝奶青_50.jpg', '50');
INSERT INTO product VALUES ('152', '荔枝烏龍', 'static/product_images/荔枝烏龍_40.jpg', '40');
INSERT INTO product VALUES ('153', '荔枝烏龍奶', 'static/product_images/荔枝烏龍奶_50.jpg', '50');
INSERT INTO product VALUES ('154', '荔枝紅茶', 'static/product_images/荔枝紅茶_40.jpg', '40');
INSERT INTO product VALUES ('155', '荔枝綠茶', 'static/product_images/荔枝綠茶_40.jpg', '40');
INSERT INTO product VALUES ('156', '荔枝青茶', 'static/product_images/荔枝青茶_40.jpg', '40');
INSERT INTO product VALUES ('157', '葡萄柚多多(季節限定)', 'static/product_images/葡萄柚多多(季節限定)_55.jpg', '55');
INSERT INTO product VALUES ('158', '葡萄柚汁(季節限定)', 'static/product_images/葡萄柚汁(季節限定)_50.jpg', '50');
INSERT INTO product VALUES ('159', '葡萄柚蜜(季節限定)', 'static/product_images/葡萄柚蜜(季節限定)_55.jpg', '55');
INSERT INTO product VALUES ('160', '蜂蜜奶綠', 'static/product_images/蜂蜜奶綠_50.jpg', '50');
INSERT INTO product VALUES ('161', '蜂蜜奶茶', 'static/product_images/蜂蜜奶茶_50.jpg', '50');
INSERT INTO product VALUES ('162', '蜂蜜奶青', 'static/product_images/蜂蜜奶青_50.jpg', '50');
INSERT INTO product VALUES ('163', '蜂蜜檸檬烏龍', 'static/product_images/蜂蜜檸檬烏龍_50.jpg', '50');
INSERT INTO product VALUES ('164', '蜂蜜檸檬紅', 'static/product_images/蜂蜜檸檬紅_50.jpg', '50');
INSERT INTO product VALUES ('165', '蜂蜜檸檬綠', 'static/product_images/蜂蜜檸檬綠_50.jpg', '50');
INSERT INTO product VALUES ('166', '蜂蜜檸檬青', 'static/product_images/蜂蜜檸檬青_50.jpg', '50');
INSERT INTO product VALUES ('167', '蜂蜜烏龍', 'static/product_images/蜂蜜烏龍_40.jpg', '40');
INSERT INTO product VALUES ('168', '蜂蜜烏龍奶', 'static/product_images/蜂蜜烏龍奶_50.jpg', '50');
INSERT INTO product VALUES ('169', '蜂蜜紅茶', 'static/product_images/蜂蜜紅茶_40.jpg', '40');
INSERT INTO product VALUES ('170', '蜂蜜綠茶', 'static/product_images/蜂蜜綠茶_40.jpg', '40');
INSERT INTO product VALUES ('171', '蜂蜜青茶', 'static/product_images/蜂蜜青茶_40.jpg', '40');
INSERT INTO product VALUES ('172', '蜜茶', 'static/product_images/蜜茶_40.jpg', '40');
INSERT INTO product VALUES ('173', '重焙烏龍拿鐵', 'static/product_images/重焙烏龍拿鐵_50.jpg', '50');
INSERT INTO product VALUES ('174', '金桔檸檬', 'static/product_images/金桔檸檬_50.jpg', '50');
INSERT INTO product VALUES ('175', '金桔檸檬蜜', 'static/product_images/金桔檸檬蜜_55.jpg', '55');
INSERT INTO product VALUES ('176', '阿華田', 'static/product_images/阿華田_40.jpg', '40');
INSERT INTO product VALUES ('177', '阿華田拿鐵', 'static/product_images/阿華田拿鐵_50.jpg', '50');
INSERT INTO product VALUES ('178', '阿薩姆紅茶', 'static/product_images/阿薩姆紅茶_30.jpg', '30');
INSERT INTO product VALUES ('179', '青茶瑪奇朵', 'static/product_images/青茶瑪奇朵_40.jpg', '40');
INSERT INTO product VALUES ('180', '鮮柚烏龍(季節限定)', 'static/product_images/鮮柚烏龍(季節限定)_50.jpg', '50');
INSERT INTO product VALUES ('181', '鮮柚紅茶(季節限定)', 'static/product_images/鮮柚紅茶(季節限定)_50.jpg', '50');
INSERT INTO product VALUES ('182', '鮮柚綠茶(季節限定)', 'static/product_images/鮮柚綠茶(季節限定)_50.jpg', '50');
INSERT INTO product VALUES ('183', '鮮柚青茶(季節限定)', 'static/product_images/鮮柚青茶(季節限定)_50.jpg', '50');
INSERT INTO product VALUES ('184', '鮮梅汁', 'static/product_images/鮮梅汁_50.jpg', '50');
INSERT INTO product VALUES ('185', '鳳梨汁', 'static/product_images/鳳梨汁_40.jpg', '40');
INSERT INTO product VALUES ('186', '黃金烏龍', 'static/product_images/黃金烏龍_30.jpg', '30');
INSERT INTO store VALUES ('92347882', '50嵐 竹田店');
INSERT INTO store VALUES ('58774146', '50嵐 三重店');
INSERT INTO store VALUES ('87096458', '50嵐 臺中店');
INSERT INTO store VALUES ('10543151', '50嵐 太平店');
INSERT INTO store VALUES ('38450584', '50嵐 阿里山店');
INSERT INTO store VALUES ('62105811', '50嵐 澎湖店');
INSERT INTO store VALUES ('11500645', '50嵐 頭份店');
INSERT INTO store VALUES ('36797598', '50嵐 梅山店');
INSERT INTO store VALUES ('47107665', '50嵐 高雄店');
INSERT INTO store VALUES ('30875279', '50嵐 光復店');
INSERT INTO store VALUES ('01947468', '50嵐 褒忠店');
INSERT INTO store VALUES ('47976065', '50嵐 連江店');
INSERT INTO store VALUES ('12594925', '50嵐 北竿店');
INSERT INTO store VALUES ('65598003', '50嵐 嘉義店');
INSERT INTO store VALUES ('49191333', '50嵐 南投店');
INSERT INTO store VALUES ('10968502', '50嵐 新北店');
INSERT INTO store VALUES ('12700938', '50嵐 竹北店');
INSERT INTO store VALUES ('15517400', '50嵐 基隆店');
INSERT INTO store VALUES ('74955825', '50嵐 桃園店');
INSERT INTO store VALUES ('56774318', '50嵐 台東店');
