USE DrinkShopDB;
GO

DELETE FROM item;
DELETE FROM [order];
DELETE FROM product;
DELETE FROM customer;
DELETE FROM store;

INSERT INTO customer VALUES ('1', '0992347882');
INSERT INTO customer VALUES ('2', '0998587741');
INSERT INTO customer VALUES ('3', '0946487096');
INSERT INTO customer VALUES ('4', '0945831054');
INSERT INTO customer VALUES ('5', '0931515384');
INSERT INTO customer VALUES ('6', '0950584866');
INSERT INTO customer VALUES ('7', '0921058112');
INSERT INTO customer VALUES ('8', '0911500645');
INSERT INTO customer VALUES ('9', '0933679759');
INSERT INTO customer VALUES ('10', '0987471076');
INSERT INTO customer VALUES ('11', '0965130875');
INSERT INTO customer VALUES ('12', '0927970194');
INSERT INTO customer VALUES ('13', '0974686479');
INSERT INTO customer VALUES ('14', '0976065521');
INSERT INTO customer VALUES ('15', '0925949256');
INSERT INTO customer VALUES ('16', '0965598003');
INSERT INTO customer VALUES ('17', '0971491913');
INSERT INTO customer VALUES ('18', '0933911096');
INSERT INTO customer VALUES ('19', '0985026012');
INSERT INTO customer VALUES ('20', '0970093831');

INSERT INTO product VALUES ('1', N'8冰烏', N'static/product_images/8冰烏_40.jpg', '40');
INSERT INTO product VALUES ('2', N'8冰紅', N'static/product_images/8冰紅_40.jpg', '40');
INSERT INTO product VALUES ('3', N'8冰綠', N'static/product_images/8冰綠_40.jpg', '40');
INSERT INTO product VALUES ('4', N'8冰茶', N'static/product_images/8冰茶_40.jpg', '40');
INSERT INTO product VALUES ('5', N'8冰青', N'static/product_images/8冰青_40.jpg', '40');
INSERT INTO product VALUES ('6', N'冰淇淋四季拿鐵', N'static/product_images/冰淇淋四季拿鐵_55.jpg', '55');
INSERT INTO product VALUES ('7', N'冰淇淋奶綠', N'static/product_images/冰淇淋奶綠_50.jpg', '50');
INSERT INTO product VALUES ('8', N'冰淇淋奶茶', N'static/product_images/冰淇淋奶茶_50.jpg', '50');
INSERT INTO product VALUES ('9', N'冰淇淋奶青', N'static/product_images/冰淇淋奶青_50.jpg', '50');
INSERT INTO product VALUES ('10', N'冰淇淋烏龍', N'static/product_images/冰淇淋烏龍_40.jpg', '40');
INSERT INTO product VALUES ('11', N'冰淇淋烏龍奶', N'static/product_images/冰淇淋烏龍奶_50.jpg', '50');
INSERT INTO product VALUES ('12', N'冰淇淋紅茶', N'static/product_images/冰淇淋紅茶_40.jpg', '40');
INSERT INTO product VALUES ('13', N'冰淇淋紅茶拿鐵', N'static/product_images/冰淇淋紅茶拿鐵_55.jpg', '55');
INSERT INTO product VALUES ('14', N'冰淇淋綠茶', N'static/product_images/冰淇淋綠茶_40.jpg', '40');
INSERT INTO product VALUES ('15', N'冰淇淋綠茶拿鐵', N'static/product_images/冰淇淋綠茶拿鐵_55.jpg', '55');
INSERT INTO product VALUES ('16', N'冰淇淋重焙烏龍拿鐵', N'static/product_images/冰淇淋重焙烏龍拿鐵_55.jpg', '55');
INSERT INTO product VALUES ('17', N'冰淇淋阿華田', N'static/product_images/冰淇淋阿華田_50.jpg', '50');
INSERT INTO product VALUES ('18', N'冰淇淋青茶', N'static/product_images/冰淇淋青茶_40.jpg', '40');
INSERT INTO product VALUES ('19', N'可可芭蕾', N'static/product_images/可可芭蕾_50.jpg', '50');
INSERT INTO product VALUES ('20', N'可可芭蕾拿鐵', N'static/product_images/可可芭蕾拿鐵_55.jpg', '55');
INSERT INTO product VALUES ('21', N'四季拿鐵', N'static/product_images/四季拿鐵_50.jpg', '50');
INSERT INTO product VALUES ('22', N'四季春青茶', N'static/product_images/四季春青茶_30.jpg', '30');
INSERT INTO product VALUES ('23', N'多多烏', N'static/product_images/多多烏_40.jpg', '40');
INSERT INTO product VALUES ('24', N'多多紅', N'static/product_images/多多紅_40.jpg', '40');
INSERT INTO product VALUES ('25', N'多多綠', N'static/product_images/多多綠_40.jpg', '40');
INSERT INTO product VALUES ('26', N'多多青', N'static/product_images/多多青_40.jpg', '40');
INSERT INTO product VALUES ('27', N'奶綠', N'static/product_images/奶綠_40.jpg', '40');
INSERT INTO product VALUES ('28', N'奶茶', N'static/product_images/奶茶_40.jpg', '40');
INSERT INTO product VALUES ('29', N'奶青', N'static/product_images/奶青_40.jpg', '40');
INSERT INTO product VALUES ('30', N'布丁四季拿鐵', N'static/product_images/布丁四季拿鐵_55.jpg', '55');
INSERT INTO product VALUES ('31', N'布丁奶綠', N'static/product_images/布丁奶綠_50.jpg', '50');
INSERT INTO product VALUES ('32', N'布丁奶茶', N'static/product_images/布丁奶茶_50.jpg', '50');
INSERT INTO product VALUES ('33', N'布丁奶青', N'static/product_images/布丁奶青_50.jpg', '50');
INSERT INTO product VALUES ('34', N'布丁烏龍奶', N'static/product_images/布丁烏龍奶_50.jpg', '50');
INSERT INTO product VALUES ('35', N'布丁紅茶拿鐵', N'static/product_images/布丁紅茶拿鐵_55.jpg', '55');
INSERT INTO product VALUES ('36', N'布丁綠茶拿鐵', N'static/product_images/布丁綠茶拿鐵_55.jpg', '55');
INSERT INTO product VALUES ('37', N'布丁重焙烏龍拿鐵', N'static/product_images/布丁重焙烏龍拿鐵_55.jpg', '55');
INSERT INTO product VALUES ('38', N'布丁阿華田', N'static/product_images/布丁阿華田_50.jpg', '50');
INSERT INTO product VALUES ('39', N'微檸檬烏龍', N'static/product_images/微檸檬烏龍_35.jpg', '35');
INSERT INTO product VALUES ('40', N'微檸檬紅茶', N'static/product_images/微檸檬紅茶_35.jpg', '35');
INSERT INTO product VALUES ('41', N'微檸檬綠茶', N'static/product_images/微檸檬綠茶_35.jpg', '35');
INSERT INTO product VALUES ('42', N'微檸檬青茶', N'static/product_images/微檸檬青茶_35.jpg', '35');
INSERT INTO product VALUES ('43', N'情人茶', N'static/product_images/情人茶_40.jpg', '40');
INSERT INTO product VALUES ('44', N'旺來烏龍', N'static/product_images/旺來烏龍_40.jpg', '40');
INSERT INTO product VALUES ('45', N'旺來紅', N'static/product_images/旺來紅_40.jpg', '40');
INSERT INTO product VALUES ('46', N'旺來綠', N'static/product_images/旺來綠_40.jpg', '40');
INSERT INTO product VALUES ('47', N'旺來青', N'static/product_images/旺來青_40.jpg', '40');
INSERT INTO product VALUES ('48', N'柚子烏龍', N'static/product_images/柚子烏龍_40.jpg', '40');
INSERT INTO product VALUES ('49', N'柚子紅', N'static/product_images/柚子紅_40.jpg', '40');
INSERT INTO product VALUES ('50', N'柚子綠', N'static/product_images/柚子綠_40.jpg', '40');
INSERT INTO product VALUES ('51', N'柚子茶', N'static/product_images/柚子茶_40.jpg', '40');
INSERT INTO product VALUES ('52', N'柚子青', N'static/product_images/柚子青_40.jpg', '40');
INSERT INTO product VALUES ('53', N'桔子汁', N'static/product_images/桔子汁_50.jpg', '50');
INSERT INTO product VALUES ('54', N'梅烏', N'static/product_images/梅烏_40.jpg', '40');
INSERT INTO product VALUES ('55', N'梅紅', N'static/product_images/梅紅_40.jpg', '40');
INSERT INTO product VALUES ('56', N'梅綠', N'static/product_images/梅綠_40.jpg', '40');
INSERT INTO product VALUES ('57', N'梅青', N'static/product_images/梅青_40.jpg', '40');
INSERT INTO product VALUES ('58', N'椰果可可芭蕾', N'static/product_images/椰果可可芭蕾_50.jpg', '50');
INSERT INTO product VALUES ('59', N'椰果可可芭蕾拿鐵', N'static/product_images/椰果可可芭蕾拿鐵_55.jpg', '55');
INSERT INTO product VALUES ('60', N'椰果四季拿鐵', N'static/product_images/椰果四季拿鐵_50.jpg', '50');
INSERT INTO product VALUES ('61', N'椰果奶綠', N'static/product_images/椰果奶綠_40.jpg', '40');
INSERT INTO product VALUES ('62', N'椰果奶茶', N'static/product_images/椰果奶茶_40.jpg', '40');
INSERT INTO product VALUES ('63', N'椰果奶青', N'static/product_images/椰果奶青_40.jpg', '40');
INSERT INTO product VALUES ('64', N'椰果烏龍', N'static/product_images/椰果烏龍_35.jpg', '35');
INSERT INTO product VALUES ('65', N'椰果烏龍奶', N'static/product_images/椰果烏龍奶_40.jpg', '40');
INSERT INTO product VALUES ('66', N'椰果紅茶', N'static/product_images/椰果紅茶_35.jpg', '35');
INSERT INTO product VALUES ('67', N'椰果紅茶拿鐵', N'static/product_images/椰果紅茶拿鐵_50.jpg', '50');
INSERT INTO product VALUES ('68', N'椰果綠茶', N'static/product_images/椰果綠茶_35.jpg', '35');
INSERT INTO product VALUES ('69', N'椰果綠茶拿鐵', N'static/product_images/椰果綠茶拿鐵_50.jpg', '50');
INSERT INTO product VALUES ('70', N'椰果重焙烏龍拿鐵', N'static/product_images/椰果重焙烏龍拿鐵_50.jpg', '50');
INSERT INTO product VALUES ('71', N'椰果阿華田', N'static/product_images/椰果阿華田_40.jpg', '40');
INSERT INTO product VALUES ('72', N'椰果阿華田拿鐵', N'static/product_images/椰果阿華田拿鐵_50.jpg', '50');
INSERT INTO product VALUES ('73', N'椰果青茶', N'static/product_images/椰果青茶_35.jpg', '35');
INSERT INTO product VALUES ('74', N'檸檬多多', N'static/product_images/檸檬多多_55.jpg', '55');
INSERT INTO product VALUES ('75', N'檸檬梅汁', N'static/product_images/檸檬梅汁_50.jpg', '50');
INSERT INTO product VALUES ('76', N'檸檬梅烏', N'static/product_images/檸檬梅烏_40.jpg', '40');
INSERT INTO product VALUES ('77', N'檸檬梅紅', N'static/product_images/檸檬梅紅_40.jpg', '40');
INSERT INTO product VALUES ('78', N'檸檬梅青', N'static/product_images/檸檬梅青_40.jpg', '40');
INSERT INTO product VALUES ('79', N'檸檬汁', N'static/product_images/檸檬汁_50.jpg', '50');
INSERT INTO product VALUES ('80', N'檸檬烏龍', N'static/product_images/檸檬烏龍_40.jpg', '40');
INSERT INTO product VALUES ('81', N'檸檬紅茶', N'static/product_images/檸檬紅茶_40.jpg', '40');
INSERT INTO product VALUES ('82', N'檸檬綠茶', N'static/product_images/檸檬綠茶_40.jpg', '40');
INSERT INTO product VALUES ('83', N'檸檬蜜', N'static/product_images/檸檬蜜_55.jpg', '55');
INSERT INTO product VALUES ('84', N'檸檬青茶', N'static/product_images/檸檬青茶_40.jpg', '40');
INSERT INTO product VALUES ('85', N'波霸可可芭蕾', N'static/product_images/波霸可可芭蕾_50.jpg', '50');
INSERT INTO product VALUES ('86', N'波霸可可芭蕾拿鐵', N'static/product_images/波霸可可芭蕾拿鐵_55.jpg', '55');
INSERT INTO product VALUES ('87', N'波霸四季拿鐵', N'static/product_images/波霸四季拿鐵_50.jpg', '50');
INSERT INTO product VALUES ('88', N'波霸奶綠', N'static/product_images/波霸奶綠_40.jpg', '40');
INSERT INTO product VALUES ('89', N'波霸奶茶', N'static/product_images/波霸奶茶_40.jpg', '40');
INSERT INTO product VALUES ('90', N'波霸奶青', N'static/product_images/波霸奶青_40.jpg', '40');
INSERT INTO product VALUES ('91', N'波霸烏龍', N'static/product_images/波霸烏龍_35.jpg', '35');
INSERT INTO product VALUES ('92', N'波霸烏龍奶', N'static/product_images/波霸烏龍奶_40.jpg', '40');
INSERT INTO product VALUES ('93', N'波霸紅茶', N'static/product_images/波霸紅茶_35.jpg', '35');
INSERT INTO product VALUES ('94', N'波霸紅茶拿鐵', N'static/product_images/波霸紅茶拿鐵_50.jpg', '50');
INSERT INTO product VALUES ('95', N'波霸綠茶', N'static/product_images/波霸綠茶_35.jpg', '35');
INSERT INTO product VALUES ('96', N'波霸綠茶拿鐵', N'static/product_images/波霸綠茶拿鐵_50.jpg', '50');
INSERT INTO product VALUES ('97', N'波霸重焙烏龍拿鐵', N'static/product_images/波霸重焙烏龍拿鐵_50.jpg', '50');
INSERT INTO product VALUES ('98', N'波霸阿華田', N'static/product_images/波霸阿華田_40.jpg', '40');
INSERT INTO product VALUES ('99', N'波霸阿華田拿鐵', N'static/product_images/波霸阿華田拿鐵_50.jpg', '50');
INSERT INTO product VALUES ('100', N'波霸青茶', N'static/product_images/波霸青茶_35.jpg', '35');
INSERT INTO product VALUES ('101', N'烏龍奶', N'static/product_images/烏龍奶_40.jpg', '40');
INSERT INTO product VALUES ('102', N'烏龍瑪奇朵', N'static/product_images/烏龍瑪奇朵_40.jpg', '40');
INSERT INTO product VALUES ('103', N'燕麥可可芭蕾', N'static/product_images/燕麥可可芭蕾_50.jpg', '50');
INSERT INTO product VALUES ('104', N'燕麥可可芭蕾拿鐵', N'static/product_images/燕麥可可芭蕾拿鐵_55.jpg', '55');
INSERT INTO product VALUES ('105', N'燕麥四季拿鐵', N'static/product_images/燕麥四季拿鐵_50.jpg', '50');
INSERT INTO product VALUES ('106', N'燕麥奶綠', N'static/product_images/燕麥奶綠_40.jpg', '40');
INSERT INTO product VALUES ('107', N'燕麥奶茶', N'static/product_images/燕麥奶茶_40.jpg', '40');
INSERT INTO product VALUES ('108', N'燕麥奶青', N'static/product_images/燕麥奶青_40.jpg', '40');
INSERT INTO product VALUES ('109', N'燕麥烏龍', N'static/product_images/燕麥烏龍_35.jpg', '35');
INSERT INTO product VALUES ('110', N'燕麥烏龍奶', N'static/product_images/燕麥烏龍奶_40.jpg', '40');
INSERT INTO product VALUES ('111', N'燕麥紅茶', N'static/product_images/燕麥紅茶_35.jpg', '35');
INSERT INTO product VALUES ('112', N'燕麥紅茶拿鐵', N'static/product_images/燕麥紅茶拿鐵_50.jpg', '50');
INSERT INTO product VALUES ('113', N'燕麥綠茶', N'static/product_images/燕麥綠茶_35.jpg', '35');
INSERT INTO product VALUES ('114', N'燕麥綠茶拿鐵', N'static/product_images/燕麥綠茶拿鐵_50.jpg', '50');
INSERT INTO product VALUES ('115', N'燕麥重焙烏龍拿鐵', N'static/product_images/燕麥重焙烏龍拿鐵_50.jpg', '50');
INSERT INTO product VALUES ('116', N'燕麥阿華田', N'static/product_images/燕麥阿華田_40.jpg', '40');
INSERT INTO product VALUES ('117', N'燕麥阿華田拿鐵', N'static/product_images/燕麥阿華田拿鐵_50.jpg', '50');
INSERT INTO product VALUES ('118', N'燕麥青茶', N'static/product_images/燕麥青茶_35.jpg', '35');
INSERT INTO product VALUES ('119', N'珍波椰青茶', N'static/product_images/珍波椰青茶_35.jpg', '35');
INSERT INTO product VALUES ('120', N'珍珠可可芭蕾', N'static/product_images/珍珠可可芭蕾_50.jpg', '50');
INSERT INTO product VALUES ('121', N'珍珠可可芭蕾拿鐵', N'static/product_images/珍珠可可芭蕾拿鐵_55.jpg', '55');
INSERT INTO product VALUES ('122', N'珍珠四季拿鐵', N'static/product_images/珍珠四季拿鐵_50.jpg', '50');
INSERT INTO product VALUES ('123', N'珍珠奶綠', N'static/product_images/珍珠奶綠_40.jpg', '40');
INSERT INTO product VALUES ('124', N'珍珠奶茶', N'static/product_images/珍珠奶茶_40.jpg', '40');
INSERT INTO product VALUES ('125', N'珍珠奶青', N'static/product_images/珍珠奶青_40.jpg', '40');
INSERT INTO product VALUES ('126', N'珍珠烏龍', N'static/product_images/珍珠烏龍_35.jpg', '35');
INSERT INTO product VALUES ('127', N'珍珠烏龍奶', N'static/product_images/珍珠烏龍奶_40.jpg', '40');
INSERT INTO product VALUES ('128', N'珍珠紅茶', N'static/product_images/珍珠紅茶_35.jpg', '35');
INSERT INTO product VALUES ('129', N'珍珠紅茶拿鐵', N'static/product_images/珍珠紅茶拿鐵_50.jpg', '50');
INSERT INTO product VALUES ('130', N'珍珠綠茶', N'static/product_images/珍珠綠茶_35.jpg', '35');
INSERT INTO product VALUES ('131', N'珍珠綠茶拿鐵', N'static/product_images/珍珠綠茶拿鐵_50.jpg', '50');
INSERT INTO product VALUES ('132', N'珍珠重焙烏龍拿鐵', N'static/product_images/珍珠重焙烏龍拿鐵_50.jpg', '50');
INSERT INTO product VALUES ('133', N'珍珠阿華田', N'static/product_images/珍珠阿華田_40.jpg', '40');
INSERT INTO product VALUES ('134', N'珍珠阿華田拿鐵', N'static/product_images/珍珠阿華田拿鐵_50.jpg', '50');
INSERT INTO product VALUES ('135', N'珍珠青茶', N'static/product_images/珍珠青茶_35.jpg', '35');
INSERT INTO product VALUES ('136', N'紅茶拿鐵', N'static/product_images/紅茶拿鐵_50.jpg', '50');
INSERT INTO product VALUES ('137', N'紅茶瑪奇朵', N'static/product_images/紅茶瑪奇朵_40.jpg', '40');
INSERT INTO product VALUES ('138', N'綠茶拿鐵', N'static/product_images/綠茶拿鐵_50.jpg', '50');
INSERT INTO product VALUES ('139', N'綠茶瑪奇朵', N'static/product_images/綠茶瑪奇朵_40.jpg', '40');
INSERT INTO product VALUES ('140', N'芒果奶綠', N'static/product_images/芒果奶綠_50.jpg', '50');
INSERT INTO product VALUES ('141', N'芒果奶茶', N'static/product_images/芒果奶茶_50.jpg', '50');
INSERT INTO product VALUES ('142', N'芒果奶青', N'static/product_images/芒果奶青_50.jpg', '50');
INSERT INTO product VALUES ('143', N'芒果烏龍', N'static/product_images/芒果烏龍_40.jpg', '40');
INSERT INTO product VALUES ('144', N'芒果烏龍奶', N'static/product_images/芒果烏龍奶_50.jpg', '50');
INSERT INTO product VALUES ('145', N'芒果紅茶', N'static/product_images/芒果紅茶_40.jpg', '40');
INSERT INTO product VALUES ('146', N'芒果綠茶', N'static/product_images/芒果綠茶_40.jpg', '40');
INSERT INTO product VALUES ('147', N'芒果青茶', N'static/product_images/芒果青茶_40.jpg', '40');
INSERT INTO product VALUES ('148', N'茉莉綠茶', N'static/product_images/茉莉綠茶_30.jpg', '30');
INSERT INTO product VALUES ('149', N'荔枝奶綠', N'static/product_images/荔枝奶綠_50.jpg', '50');
INSERT INTO product VALUES ('150', N'荔枝奶茶', N'static/product_images/荔枝奶茶_50.jpg', '50');
INSERT INTO product VALUES ('151', N'荔枝奶青', N'static/product_images/荔枝奶青_50.jpg', '50');
INSERT INTO product VALUES ('152', N'荔枝烏龍', N'static/product_images/荔枝烏龍_40.jpg', '40');
INSERT INTO product VALUES ('153', N'荔枝烏龍奶', N'static/product_images/荔枝烏龍奶_50.jpg', '50');
INSERT INTO product VALUES ('154', N'荔枝紅茶', N'static/product_images/荔枝紅茶_40.jpg', '40');
INSERT INTO product VALUES ('155', N'荔枝綠茶', N'static/product_images/荔枝綠茶_40.jpg', '40');
INSERT INTO product VALUES ('156', N'荔枝青茶', N'static/product_images/荔枝青茶_40.jpg', '40');
INSERT INTO product VALUES ('157', N'葡萄柚多多(季節限定)', N'static/product_images/葡萄柚多多(季節限定)_55.jpg', '55');
INSERT INTO product VALUES ('158', N'葡萄柚汁(季節限定)', N'static/product_images/葡萄柚汁(季節限定)_50.jpg', '50');
INSERT INTO product VALUES ('159', N'葡萄柚蜜(季節限定)', N'static/product_images/葡萄柚蜜(季節限定)_55.jpg', '55');
INSERT INTO product VALUES ('160', N'蜂蜜奶綠', N'static/product_images/蜂蜜奶綠_50.jpg', '50');
INSERT INTO product VALUES ('161', N'蜂蜜奶茶', N'static/product_images/蜂蜜奶茶_50.jpg', '50');
INSERT INTO product VALUES ('162', N'蜂蜜奶青', N'static/product_images/蜂蜜奶青_50.jpg', '50');
INSERT INTO product VALUES ('163', N'蜂蜜檸檬烏龍', N'static/product_images/蜂蜜檸檬烏龍_50.jpg', '50');
INSERT INTO product VALUES ('164', N'蜂蜜檸檬紅', N'static/product_images/蜂蜜檸檬紅_50.jpg', '50');
INSERT INTO product VALUES ('165', N'蜂蜜檸檬綠', N'static/product_images/蜂蜜檸檬綠_50.jpg', '50');
INSERT INTO product VALUES ('166', N'蜂蜜檸檬青', N'static/product_images/蜂蜜檸檬青_50.jpg', '50');
INSERT INTO product VALUES ('167', N'蜂蜜烏龍', N'static/product_images/蜂蜜烏龍_40.jpg', '40');
INSERT INTO product VALUES ('168', N'蜂蜜烏龍奶', N'static/product_images/蜂蜜烏龍奶_50.jpg', '50');
INSERT INTO product VALUES ('169', N'蜂蜜紅茶', N'static/product_images/蜂蜜紅茶_40.jpg', '40');
INSERT INTO product VALUES ('170', N'蜂蜜綠茶', N'static/product_images/蜂蜜綠茶_40.jpg', '40');
INSERT INTO product VALUES ('171', N'蜂蜜青茶', N'static/product_images/蜂蜜青茶_40.jpg', '40');
INSERT INTO product VALUES ('172', N'蜜茶', N'static/product_images/蜜茶_40.jpg', '40');
INSERT INTO product VALUES ('173', N'重焙烏龍拿鐵', N'static/product_images/重焙烏龍拿鐵_50.jpg', '50');
INSERT INTO product VALUES ('174', N'金桔檸檬', N'static/product_images/金桔檸檬_50.jpg', '50');
INSERT INTO product VALUES ('175', N'金桔檸檬蜜', N'static/product_images/金桔檸檬蜜_55.jpg', '55');
INSERT INTO product VALUES ('176', N'阿華田', N'static/product_images/阿華田_40.jpg', '40');
INSERT INTO product VALUES ('177', N'阿華田拿鐵', N'static/product_images/阿華田拿鐵_50.jpg', '50');
INSERT INTO product VALUES ('178', N'阿薩姆紅茶', N'static/product_images/阿薩姆紅茶_30.jpg', '30');
INSERT INTO product VALUES ('179', N'青茶瑪奇朵', N'static/product_images/青茶瑪奇朵_40.jpg', '40');
INSERT INTO product VALUES ('180', N'鮮柚烏龍(季節限定)', N'static/product_images/鮮柚烏龍(季節限定)_50.jpg', '50');
INSERT INTO product VALUES ('181', N'鮮柚紅茶(季節限定)', N'static/product_images/鮮柚紅茶(季節限定)_50.jpg', '50');
INSERT INTO product VALUES ('182', N'鮮柚綠茶(季節限定)', N'static/product_images/鮮柚綠茶(季節限定)_50.jpg', '50');
INSERT INTO product VALUES ('183', N'鮮柚青茶(季節限定)', N'static/product_images/鮮柚青茶(季節限定)_50.jpg', '50');
INSERT INTO product VALUES ('184', N'鮮梅汁', N'static/product_images/鮮梅汁_50.jpg', '50');
INSERT INTO product VALUES ('185', N'鳳梨汁', N'static/product_images/鳳梨汁_40.jpg', '40');
INSERT INTO product VALUES ('186', N'黃金烏龍', N'static/product_images/黃金烏龍_30.jpg', '30');

INSERT INTO store VALUES ('92347882', N'50嵐 竹田店');
INSERT INTO store VALUES ('58774146', N'50嵐 三重店');
INSERT INTO store VALUES ('87096458', N'50嵐 臺中店');
INSERT INTO store VALUES ('10543151', N'50嵐 太平店');
INSERT INTO store VALUES ('38450584', N'50嵐 阿里山店');
INSERT INTO store VALUES ('62105811', N'50嵐 澎湖店');
INSERT INTO store VALUES ('11500645', N'50嵐 頭份店');
INSERT INTO store VALUES ('36797598', N'50嵐 梅山店');
INSERT INTO store VALUES ('47107665', N'50嵐 高雄店');
INSERT INTO store VALUES ('30875279', N'50嵐 光復店');
INSERT INTO store VALUES ('01947468', N'50嵐 褒忠店');
INSERT INTO store VALUES ('47976065', N'50嵐 連江店');
INSERT INTO store VALUES ('12594925', N'50嵐 北竿店');
INSERT INTO store VALUES ('65598003', N'50嵐 嘉義店');
INSERT INTO store VALUES ('49191333', N'50嵐 南投店');
INSERT INTO store VALUES ('10968502', N'50嵐 新北店');
INSERT INTO store VALUES ('12700938', N'50嵐 竹北店');
INSERT INTO store VALUES ('15517400', N'50嵐 基隆店');
INSERT INTO store VALUES ('74955825', N'50嵐 桃園店');
INSERT INTO store VALUES ('56774318', N'50嵐 台東店');

